# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Editor
export EDITOR=vim

# Load alias
source ~/.dotfiles/zsh/alias

export FZF_DEFAULT_COMMAND='ag -l -g ""'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

###-tns-completion-start-###
if [ -f /Users/rma/.tnsrc ]; then 
    source /Users/rma/.tnsrc 
fi
###-tns-completion-end-###
